package com.gca.Models.Enumeration;

public enum TypeOperation {
    CHIRURGIE_THORACIQUE,
    CHIRURGIE_MAXILLOFACIALE,
    CHIRURGIE_RÉPARATRICE,
    CHIRURGIE_PÉDIATRIQUE,
    CHIRURGIE_VASCULAIRE,
    CHIRURGIE_ORTHOPÉDIQUE,
    CHIRURGIE_VISCÉRALE_ET_DIGESTIVE,
    NEUROCHIRURGIE,
    CHIRURGIE_CARDIAQUE
}